---

- name: 'Update apt package cache'
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_pkg_mgr == 'apt'

- name: 'Fix dnf ansible/issues/14427'
  shell: dnf install -y python-dnf
  when: ansible_pkg_mgr == 'dnf'

- include_vars: "{{ item }}"
  with_first_found:
   - "{{ansible_os_family}}.yml"
   - "{{ansible_pkg_mgr}}.yml"

- name: 'Install pkg dependencies'
  package:
    pkg: "{{ item }}"
    state: present
  with_items: '{{duplicity_pkg_dependencies}}'
  when: duplicity_install_type == "pkg"

- name: 'Install pip packages'
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state}}"
  with_items: '{{duplicity_pip_packages}}'
